### ISSUE TITLE
ヤマタクさんへ

### ISSUE THREAD

**Issue by Tshi66** [Tshi66/PFpractice#9]
先日の初回面談時に、
>- 技術的なメンタリング
>  1. PRベースでレビューをしていくスタイル
>  2. ヤマタクが既存プロジェクト全体を見て指摘箇所をissueとして起票していく

このように掲げていただけたと思います。
ですので、2.既存プロジェクト全体を見て指摘箇所をissueとして起票。をしていただければと、面談時に話させていただきました。

そのため、現在
**コードレビューをしていただくために、
私が現状できる範囲でリファクタリングを行っています。**

ですが、予想よりも多くの時間を割いていますので、
以下のスクショのように「リファクタリング」のコミットメッセージのあるファイルから目を通していただけると良いかな？と思います！
<img width="463" alt="スクリーンショット 2020-01-25 0 44 02" src="https://user-images.githubusercontent.com/47974150/73081911-cb867c00-3f0b-11ea-8b4f-b091662480a9.png">

**Comment by yamataku29** [comment]
なるほどです！
では一旦`リファクタリング`のコミットからレビュー開始しますね😊
